### ISSUE TITLE
Color of the images after running extract.py

### ISSUE THREAD

**Issue by himansh1314** [thatbrguy/Dehaze-GAN#13]
The Color of the images after running extract.py doesn't seem right. Most of the images appear really blueish. Maybe it's some issue with opencv having changing the configuration from RGB to BGR. Please have a look at it

**Comment by thatbrguy** [comment]
<del> I just ran the script, looks like you are right, they do have a blueish tint. As you noticed, you could convert both the `fog` and `img` variables to BGR (lines 30, 31 in `extract.py`) before saving them so that OpenCV saves them appropriately.</del>

<del> Since this repository also serves as a quick way to replicate or test out the pre-trained model (which was probably trained on the blue-tinted images), I have decided not to modify `extract.py`. However I will mention this issue in the readme file so people can modify it if they want to. Thanks for the heads up! </del>

**UPDATE (June 2021):** Please ignore the above suggestions and analysis which is stricken through. On a recent analysis I made a few observations about the colorspace issues in general. Please refer to the document [issue.md](https://github.com/thatbrguy/Dehaze-GAN/blob/master/issue.md) instead for a detailed and accurate explanation of the colorspace issue. I apologize for the inconvenience caused due to the issue.
